### ISSUE TITLE
Interested in participating

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/equity-and-inclusion#1]
Interested in contributing. Maybe after some more advertising we could have a call on this? Too scattered right now to comment more here the second.

**Comment by ChristinaLK** [comment]
Seconded. I don't know what I can contribute but would love to be part of more conversations about these topics.

**Comment by kariljordan** [comment]
Absolutely. This is truly a placeholder, and this repo and our efforts around equity and inclusion will continue to grow. I'm happy you both are interested in being involved in the conversation. Will ping you as things come up!

**Comment by kariljordan** [comment]
@JasonJWilliamsNY @ChristinaLK I wanted to bring your attention to the community discussion I'm hosting 21-22 May. I'll be talking about the Equity, Inclusion, and Accessibility Roadmap and how everyone can contribute. Sign up on the ]community-discussions etherpad](https://pad.carpentries.org/community-discussions) around line 87. I hope you can make it! I'll close this issue now because we are finally ready to get to work!
